#!/bin/bash -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/rockmongo

# mongodb: create admin user before enabling auth
/usr/lib/inithooks/bin/mongodb.py --pass="$ADMIN_PASS" --current-pass=""

# mongodb: enable auth and bind to all interfaces
CONF=/etc/mongodb.conf
sed -i "s|^#auth.*|auth = true|" $CONF
sed -i "s|^bind_ip.*|bind_ip = 0.0.0.0|" $CONF

# mongo-php: build and install driver
cd $SRC/mongo-php-driver
phpize
./configure
make install
echo "extension=mongo.so" > /etc/php5/conf.d/mongo.ini
cd /; rm -rf $SRC/mongo-php-driver

# rockmongo: plugins, configure, and enable in lighttpd
unzip $SRC/mapreduce-*.zip -d $WEBROOT/app/plugins
unzip $SRC/sharding-*.zip -d $WEBROOT/app/plugins
unzip $SRC/systemjs-*.zip -d $WEBROOT/app/plugins
rm $SRC/mapreduce-*.zip
rm $SRC/sharding-*.zip
rm $SRC/systemjs-*.zip

CONF=$WEBROOT/config.php
sed -i "s|\[\"mongo_auth\"\].*|[\"mongo_auth\"] = true;|" $CONF

cat >$WEBROOT/app/configs/rplugin.php<<EOF
<?php
\$plugins["mapreduce"]["enabled"] = 1;
\$plugins["sharding"]["enabled"] = 1;
\$plugins["systemjs"]["enabled"] = 1;
?>
EOF

chown -R root:root $WEBROOT

lighty-disable-mod ssl
lighty-enable-mod rockmongo

